version: '3'
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
      - cache

  database:
    image: "postgres:15"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drop_note_database
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    expose:
      - "6379"
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - /path/to/redis-persistence:/bitnami/redis/data
volumes:
  database-data:
