name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      matrix:
        node-version: [13.x,14.x,15.x,16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name : Run Migrations
        env:
        PORT: 3000
          dbport: 5432
          user: postgres
          password: postgres
          host: localhost
          database: testdb
          REDIS_URL: redis
          REDIS_PORT: 6379
          REDIS_HOST_PASSWORD: redis
        run: npm run migrate
      - name: Run Tests
        env:
          dbport: 5432
          user: postgres
          password: postgres
          host: localhost
          database: testdb
          REDIS_URL: redis
          REDIS_PORT: 6379
          REDIS_HOST_PASSWORD: redis
        run: npm test